[[sound]]
source = "logo.wav"
outfile = "boot_chime.c"
symbol = "sound_boot_chime"
sample_rate = 16000
channels = 1
bits_per_sample = 16
normalize_peak = true
headroom_db = 5.0
usage = "Boot chime"


[[sound]]
source = "failure.wav"
outfile = "failure.c"
symbol = "sound_failure"
sample_rate = 16000
channels = 1
bits_per_sample = 16
normalize_peak = true
headroom_db = 5.0
usage = "Failure laugh"


[[sound]]
source = "scott_greeting.wav"
outfile = "scott_greeting.c"
symbol = "sound_scott_greeting"
sample_rate = 16000
channels = 1
bits_per_sample = 16
normalize_peak = true
headroom_db = 5.0
usage = "Scott greeting"
